[build]
publish = "public"
command = "hugo --gc --minify --theme paper"
[context.production.environment]
HUGO_VERSION = "v0.77.0/extended"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
[context.split1]
command = "hugo --gc --minify --enableGitInfo --theme paper"
[context.split1.environment]
HUGO_VERSION = "v0.77.0/extended"
HUGO_ENV = "production"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL --theme paper"
[context.deploy-preview.environment]
HUGO_VERSION = "v0.77.0/extended"
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL --theme paper"
[context.branch-deploy.environment]
HUGO_VERSION = "v0.77.0/extended"
[context.next.environment]
HUGO_ENABLEGITINFO = "true"